# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shoppingmall # 자신의 환경에 맞게 변경 가능
    username: team1 # 자신의 환경에 맞게 변경 가능
    password: team111 # 자신의 환경에 맞게 변경 가능


  jackson:
    default-property-inclusion: non_null # DTO에서 null 값인 필드 전송 안됨

  # 임의로 설정한 변수
  # spring security에서 JWT 토큰 만들때 사용
  jwt:
    secret: eliceproject2eliceproject2eliceproject2eliceproject2


  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: none # create 처음 실행시 sql 테이블 생성 이후에는 none 으로 설정
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

    jackson:
      default-property-inclusion: non_null


#logging:
#  level:
#    root: DEBUG

